### ISSUE TITLE
Make /bot possepic needs to return a random image of all image instead of person because joeypuff is a baby

### ISSUE THREAD

**Issue by drewlander** [tomdisher/possebot#8]

**Comment by Joeboku** [comment]
It's not truly a random possepic if all possepic don't have the same chance of popping up. In it's current state it's a random pic of a random posseperson.

**Comment by drewlander** [comment]
we care about people and all people have the same chance. have a heart

**Comment by Joeboku** [comment]
All posse people are not created equal. Some are half sized *looks at Meekle* But all posse pics should be. #possepicsmatter

**Comment by drewlander** [comment]
since meekle has the most pictures, making this choose a random image from all the images, automatically biases the results towards him, making 
`/bot possepic`
equivalent to
`/bot possepic meekle`

Until there are nearly the same number of images for all people, and keeping feelings out of it, this will not be fixed.
